rule Sunburst
{

	meta:
		author = "Generated by Malcore Yara Generator (MYG) on 12-16-2020 (contact@penetrum.com)"
		ref = "https://penetrum.com"
		copyright = "Penetrum, LLC"
		sha256 = "ce77d116a074dab7a22a0fd4f2c1ab475f16eec42e1ded3c0b0aa8211fe858d6"
	strings:
		$specific1 = "SolarWinds.Orion.Core.BusinessLayer."
		$specific2 = "_CorDllMain"
		$specific3 = "advapi32.dll"
		$specific4 = "http://ocsp.digicert.com0C"
		$specific5 = "http://ocsp.digicert.com0O"
		$specific6 = "http://s1.symcb.com/pca3-g5.crl0"
		$specific7 = "C:\\buildAgent\\temp\\buildTmp\\Obj\"
		$specific8 = "4.0.0.0"
		$specific9 = "$14e64ecd-0839-4fb5-a727-69a46cce618"
		$matchable1 = " '@y+.A8f"
		$matchable10 = "!IrU7"
		$matchable11 = "!Method"
		$matchable12 = "!This"
		$matchable13 = "!^Z{"
		$matchable14 = "!b%#"
		$matchable15 = "#&~`"
		$matchable16 = "#0!0"
		$matchable17 = "#Blob"
		$matchable18 = "#GUID"
		$matchable19 = "#K%3"
		$matchable2 = " '@y+5"
		$matchable20 = "#Strings"
		$matchable21 = "$@(x"
		$matchable22 = "$@(y"
		$matchable23 = "${MEAN}+2*${STD_DEV}T"
		$matchable24 = "${MEAN}+3*${STD_DEV}T"
		$matchable25 = "${MEAN}-2*${STD_DEV}T"
		$matchable26 = "${MEAN}-3*${STD_DEV}T"
		$matchable3 = " )UU"
		$matchable4 = " H8y&;"
		$matchable5 = " Lm|"
		$matchable6 = " n;y(;L"
		$matchable7 = " sT'"
		$matchable8 = " w/^"
		$matchable9 = " }`&j;"

	condition:
		9 of ($specific*) and 13 of ($matchable*)
}